### ISSUE TITLE
Why did you remove Escherichia phage phiX sequences in preprocessing step?

### ISSUE THREAD

**Issue by zkskek321** [RChGO/VMGC#1]
Hi, I'm microbiome researcher in South Korea.

Thank you for this amazing study.

While reading your paper, I'm wondering why did you remove phiX sequences.

(1) Why did you remove Escherichia phage phiX174?
(2) Why didn't you remove another virus sequences?
(3) Should we remove this viral genome for another microbial study? (e.g.) gut microbiome study

Thank a lot.

**Comment by RChGO** [comment]
> Hi, I'm microbiome researcher in South Korea.
> 
> Thank you for this amazing study.
> 
> While reading your paper, I'm wondering why did you remove phiX sequences.
> 
> (1) Why did you remove Escherichia phage phiX174? (2) Why didn't you remove another virus sequences? (3) Should we remove this viral genome for another microbial study? (e.g.) gut microbiome study
> 
> Thank a lot.

1. PhiX174 DNA is frequently used as a quality control sequence in Illumina sequencing. Sometimes, during Illumina sequencing runs, PhiX174 DNA gets mixed with the user's DNA samples. In the samples we analyzed, some projects (e.g., PRJNA779415) had all samples containing the complete PhiX174 genome, while other projects (e.g., PRJNA771720) had none. Therefore, it is highly likely that the presence of this genome is due to artificial addition rather than originating from the samples themselves. We believe it should be excluded.

2. We do not rule out the possibility that some viruses, such as the pepper mild mottle virus mentioned in the article, could also be contaminants. However, in the absence of definitive evidence proving that these viruses are contaminants, we have chosen to retain the corresponding genomes.

3. Personally, I believe that PhiX174 DNA should be excluded in most studies, including gut virome research (e.g., https://doi.org/10.1016/j.chom.2020.08.003). As for other viral genomes, to my knowledge, they have not been specifically treated in this manner.

**Comment by zkskek321** [comment]
Thanks a lot!!!
